
1. **Active customers by city**
   Find the total number of active customers in each city.
  
2. **Top cities by number of orders**
   Find the top five cities that have the highest number of orders.
  
3. **Category wise total revenue**
   Calculate total revenue generated by each product category.
  
4. **Average order value per customer**
   Calculate the average order value for each customer.
   
5. **Cancelled orders percentage**
   Calculate the percentage of orders that were cancelled.

6. **Paid but not delivered orders**
   Find customers who have completed payment but whose orders are not delivered.
  
7. **Monthly revenue trend**
   Analyze monthly revenue for the last three years.

8. **Top customers by lifetime spending**
   Find the top ten customers based on total spending.
9. **Most used payment method and success rate**
   Find the most frequently used payment method and its success rate.

10. **Products ordered despite zero stock**
    Find products that had zero stock but were still ordered.
   