---SQL PROJECT NAME:-Online Store Sales and Customer Analysis System---
SELECT * FROM products;
SELECT * FROM customers;
SELECT * FROM orders;
SELECT * FROM order_items;
SELECT * FROM payments;


--1.Check table row count
SELECT COUNT(*) AS total_rows FROM customers;
SELECT COUNT(*) AS total_rows FROM products;
SELECT COUNT(*) AS total_rows FROM orders;
SELECT COUNT(*) AS total_rows FROM order_items;
SELECT COUNT(*) AS total_rows FROM payments;

--2. Check null values column wise
SELECT
    COUNT(*) FILTER (WHERE customer_id IS NULL) AS customer_id_nulls,
    COUNT(*) FILTER (WHERE customer_name IS NULL) AS customer_name_nulls,
    COUNT(*) FILTER (WHERE email IS NULL) AS email_nulls,
    COUNT(*) FILTER (WHERE phone_number IS NULL) AS phone_number_nulls,
    COUNT(*) FILTER (WHERE city IS NULL) AS city_nulls,
    COUNT(*) FILTER (WHERE signup_date IS NULL) AS signup_date_nulls
FROM customers

-- Check null values column wise
SELECT 
     COUNT(*) FILTER (WHERE order_item_id IS NULL ) AS order_item_id_nulls,
	 COUNT(*) FILTER (WHERE order_id IS NULL) AS order_id_nulls,
	 COUNT(*) FILTER (WHERE product_id IS NULL) AS porduct_id_nulls,
	 COUNT(*) FILTER (WHERE quantity IS NULL) AS quantity_nulls,
	 COUNT(*) FILTER (WHERE unit_price IS NULL) AS unit_price_nulls,
	 COUNT(*) FILTER (WHERE discount IS NULL) AS discount_nulls,
	 COUNT(*) FILTER (WHERE tax_percent IS NULL) AS tax_percent,
	 COUNT(*) FILTER (WHERE warehouse IS NULL)  AS warehouse_nulls,
	 COUNT(*) FILTER (WHERE dispatch_status IS NULL) AS dispatch_status_nulls
FROM order_items

-- Check null values column wise

SELECT 
     COUNT(*) FILTER (WHERE order_id IS NULL) AS  order_id_nulls,
	 COUNT(*) FILTER (WHERE customer_id IS NULL) AS customer_id_nulls,
	 COUNT(*) FILTER (WHERE order_date IS NULL) AS order_date_nulls,
	 COUNT(*) FILTER (WHERE order_status IS NULL) AS order_status_nulls,
	 COUNT(*) FILTER (WHERE shipping_address IS NULL) AS shipping_address_nulls,
	 COUNT(*) FILTER (WHERE city IS NULL) AS city_nulls,
	 COUNT(*) FILTER (WHERE states IS NULL) AS states_nulls,
	 COUNT(*) FILTER (WHERE postal_code IS NULL) AS postal_code_nulls,
	 COUNT(*) FILTER (WHERE shipping_method IS NULL) AS shipping_method_nulls,
	 COUNT(*) FILTER (WHERE estimated_delivery_days IS NULL) AS estimated_delivery_days_nulls
FROM orders

-- Check null values column wise

SELECT 
     COUNT(*) FILTER (WHERE payment_id IS NULL) AS payment_id_nulls,
	 COUNT(*) FILTER (WHERE order_id IS NULL) AS order_id_nulls,
	 COUNT(*) FILTER (WHERE payment_date IS NULL) AS payment_datea_nulls,
	 COUNT(*) FILTER (WHERE payment_method IS NULL) AS payment_method_nulls,
	 COUNT(*) FILTER (WHERE payment_status IS NULL) AS payment_status_nulls,
	 COUNT(*) FILTER (WHERE transaction_amount IS NULL)  AS transaction_amount_nulls,
	 COUNT(*) FILTER (WHERE bank_name IS NULL) AS bank_name_nulls,
	 COUNT(*) FILTER (WHERE transaction_reference IS NULL) AS transaction_reference_nulls,
	 COUNT(*) FILTER (WHERE refund_status IS NULL) AS refund_status_nulls,
	 COUNT(*) FILTER (WHERE currency IS  NULL) AS currency_nulls
FROM payments
 
-- Check null values column wise

SELECT  
     COUNT(*) FILTER (WHERE product_id IS NULL) AS product_id_nulls,
	 COUNT(*) FILTER (WHERE product_name IS NULL) AS product_name_nulls,
	 COUNT(*) FILTER (WHERE category IS NULL) AS category_nulls,
	 COUNT(*) FILTER (WHERE brand IS NULL) AS  brand_nulls,
	 COUNT(*) FILTER (WHERE price IS NULL) AS price_nulls,
	 COUNT(*) FILTER (WHERE stock_quantity IS NULL) AS stock_quantity,
	 COUNT(*) FILTER (WHERE supplier_name IS NULL) AS supplier_name_nulls,
	 COUNT(*) FILTER (WHERE rating IS NULL) AS rating_nulls,
	 COUNT(*) FILTER (WHERE created_date IS NULL) AS created_date_nulls,
	 COUNT(*) FILTER (WHERE product_status IS NULL) AS product_status
FROM products;
--3. Check duplicate primary keys
SELECT customer_id, COUNT(*)
FROM customers
GROUP BY customer_id
HAVING COUNT(*) > 1


----10 BUSINESS PROBELMS & SOLUTIONS-----

--1. **Active customers by city**
--Find the total number of active customers in each city.

SELECT 
      city,
	  SUM(customer_id) as total_customers
FROM customers
WHERE customer_status = 'Active'
GROUP BY city
ORDER BY total_customers DESC

--2. **Top cities by number of orders**
--Find the top five cities that have the highest number of orders.
SELECT 
     city,
	 COUNT(order_id) AS total_orders
FROM orders
GROUP BY city
ORDER BY total_orders DESC
LIMIT 5

--3. **Category wise total revenue**
--Calculate total revenue generated by each product category.

SELECT
     p.category,
     SUM(o.quantity * o.unit_price) as total_revenue
FROM products p
JOIN order_items o
on p.product_id = o.product_id
GROUP BY p.category
ORDER BY total_revenue

--4. **Average order value per customer**
--Calculate the average order value for each customer.
   
SELECT
    c.customer_name,
    AVG(order_total) AS average_order_value
FROM customers c
JOIN (
    SELECT
        o.order_id,
        o.customer_id,
        SUM(oi.quantity * oi.unit_price) AS order_total
    FROM orders o
    JOIN order_items oi
    ON o.order_id = oi.order_id
    GROUP BY o.order_id, o.customer_id
) t
ON c.customer_id = t.customer_id
GROUP BY c.customer_name
ORDER BY average_order_value DESC;
    
--5.Cancelled orders percentageat were cancelled.
SELECT 
     (COUNT(CASE WHEN order_status = 'Cancelled' THEN 1 END) * 100.0) / COUNT(*) AS CANCELLED_ORDERS	  
from orders

--6. **Paid but not delivered orders**
--Find customers who have completed payment but whose orders are not delivered.
  
SELECT 
     c.customer_name,
	 o.order_status,
	 p.payment_status
FROM customers c
JOIN orders o
ON   c.customer_id = o.customer_id
JOIN payments p
ON p.order_id=o.order_id
WHERE p.payment_status = 'Success'
AND o.order_status in ('Placed','Shipped')

--7. **Monthly revenue trend**
--Analyze monthly revenue for the last three years.
   
SELECT
      EXTRACT(YEAR FROM o.order_date) AS Years,
	  EXTRACT(MONTH FROM o.order_date) AS Months,
	  SUM(oi.quantity * oi.unit_price) AS monthly_revnue
FROM orders o
JOIN order_items oi
ON o.order_id = oi.order_id
WHERE o.order_date >= CURRENT_DATE - INTERVAL '3 years'
GROUP BY 
       EXTRACT(YEAR FROM o.order_date),
	   EXTRACT(MONTH FROM o.order_date)
ORDER BY Years,Months

--8. **Top customers by lifetime spending**
--Find the top ten customers based on total spending.
  

SELECT 
      c.customer_name,
	  SUM(oi.unit_price) AS total_spending
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY c.customer_name
ORDER BY total_spending DESC
LIMIT 10

--9. **Most used payment method and success rate**
--Find the most frequently used payment method and its success rate.
   
SELECT
     payment_method,
	 COUNT(*) AS total_transactions,
	 COUNT(CASE WHEN payment_status = 'Success' THEN 1 END) AS successful_transaction,
	 (COUNT(CASE WHEN payment_status = 'Success' THEN 1 END)* 100.0) / COUNT(*) AS success_rate
FROM payments
WHERE payment_method IN ('UPI','Card','Net Banking')
GROUP BY payment_method
ORDER BY total_transactions DESC

--10. **Products ordered despite zero stock**
--Find products that had zero stock but were still ordered.
SELECT DISTINCT
    p.product_id,
    p.product_name,
    p.stock_quantity
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
WHERE p.stock_quantity = 0;